int enableColor(void);
int areEqual(double a, double b);
void positiveIntVerify(int *input, int *arr, int arrLen);
void doubleVerify(int numColumn, int numRow, double *matrix, char *str);
void getRowAndColumnNum(int *numRow, int *numColumn);
void displayMatrix(int numColumn, int numRow, double *matrix);
void displaySolution(int size, double *solution);
void setIdentityMatrix(int n, double *matrix);
void arrayCopy(int numRow, int numColumn, double *srcMatrix, double *destMatrix);
void switchColumns(int numRow, int numColumn, int column, double *matrix, double *arrColumn);
void switchRows(int numColumn, int row1, int row2, double *matrix);
double* separateColumn(int numRow, int numColumn, int column, double *matrix, double *arrColumn);
int printOpeningAndGetNum(void);
void printText(int num);