int enableColor(void);
void swap(double* num1, double* num2);
int areEqual(double a, double b);
void positiveIntVerify(int* input, int* arr, int arrLen);
void doubleVerify(int numRow, int numColumn, double* matrix, char* str);
void getRowAndColumnNum(int* numRow, int* numColumn);
void displayMatrix(int numRow, int numColumn, double* matrix);
void displaySolution(int size, double* solution);
void setIdentityMatrix(int n, double* matrix);
void arrayCopy(int numRow, int numColumn, double* srcMatrix, double* destMatrix);
void switchColumns(int numRow, int numColumn, int column, double* matrix, double* arrColumn);
void switchRows(int row1, int row2, int numColumn, double* matrix);
double* separateColumn(int numRow, int numColumn, int column, double* matrix, double* arrColumn);
int printOpeningAndGetNum(void);
void printText(int num);